services:
  - type: web
    name: odoo14
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: dpg-d054uuadbo4c73bgmsu0-a
      - key: USER
        value: odoodb
      - key: PASSWORD
        value: ogLJI2GKItf9zrhE86AuMGXczy7SweiH
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 1
